name: flutter_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_verification_code: ^1.1.6
  image_picker: ^0.8.7+4
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
